/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as GamesRouteImport } from './routes/games'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesPopRouteImport } from './routes/games.pop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesPopRoute = GamesPopRouteImport.update({
  id: '/pop',
  path: '/pop',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/games': typeof GamesRouteWithChildren
  '/order-complete': typeof OrderCompleteRoute
  '/shop': typeof ShopRoute
  '/games/match': typeof GamesMatchRoute
  '/games/pop': typeof GamesPopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/games': typeof GamesRouteWithChildren
  '/order-complete': typeof OrderCompleteRoute
  '/shop': typeof ShopRoute
  '/games/match': typeof GamesMatchRoute
  '/games/pop': typeof GamesPopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/games': typeof GamesRouteWithChildren
  '/order-complete': typeof OrderCompleteRoute
  '/shop': typeof ShopRoute
  '/games/match': typeof GamesMatchRoute
  '/games/pop': typeof GamesPopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/games'
    | '/order-complete'
    | '/shop'
    | '/games/match'
    | '/games/pop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/games'
    | '/order-complete'
    | '/shop'
    | '/games/match'
    | '/games/pop'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/games'
    | '/order-complete'
    | '/shop'
    | '/games/match'
    | '/games/pop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  GamesRoute: typeof GamesRouteWithChildren
  OrderCompleteRoute: typeof OrderCompleteRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/match': {
      id: '/games/match'
      path: '/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/pop': {
      id: '/games/pop'
      path: '/pop'
      fullPath: '/games/pop'
      preLoaderRoute: typeof GamesPopRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesMatchRoute: typeof GamesMatchRoute
  GamesPopRoute: typeof GamesPopRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesMatchRoute: GamesMatchRoute,
  GamesPopRoute: GamesPopRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  GamesRoute: GamesRouteWithChildren,
  OrderCompleteRoute: OrderCompleteRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
