/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesPopRouteImport } from './routes/games.pop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/games/match',
  path: '/games/match',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPopRoute = GamesPopRouteImport.update({
  id: '/games/pop',
  path: '/games/pop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-complete': typeof OrderCompleteRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/games/match': typeof GamesMatchRoute
  '/games/pop': typeof GamesPopRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-complete': typeof OrderCompleteRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/games/match': typeof GamesMatchRoute
  '/games/pop': typeof GamesPopRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-complete': typeof OrderCompleteRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/games/match': typeof GamesMatchRoute
  '/games/pop': typeof GamesPopRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/order-complete'
    | '/orders'
    | '/shop'
    | '/games/match'
    | '/games/pop'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/order-complete'
    | '/orders'
    | '/shop'
    | '/games/match'
    | '/games/pop'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/order-complete'
    | '/orders'
    | '/shop'
    | '/games/match'
    | '/games/pop'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  OrdersRoute: typeof OrdersRoute
  ShopRoute: typeof ShopRoute
  GamesMatchRoute: typeof GamesMatchRoute
  GamesPopRoute: typeof GamesPopRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/match': {
      id: '/games/match'
      path: '/games/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/pop': {
      id: '/games/pop'
      path: '/games/pop'
      fullPath: '/games/pop'
      preLoaderRoute: typeof GamesPopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  OrdersRoute: OrdersRoute,
  ShopRoute: ShopRoute,
  GamesMatchRoute: GamesMatchRoute,
  GamesPopRoute: GamesPopRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
